title: Blog
description: 小白龙的前端记录
locales:
  /:
    lang: zh-CN
    title: Blog
    description: 小白龙的前端记录
head: 
  -
    - link
    -
      rel: icon
      href: /avatar.png
themeConfig :
  logo: /avatar.png
  nav:
    - text: 读书笔记
      link: https://reading.xblcity.com
    - text: Github
      link: https://github.com/xblcity
  sidebar: 
    - title: 介绍
      path: /
    - title: JS基础
      collapsable: false
      sidebarDepth: 2
      children:
        - /js/scope-closures
        - /js/this
        - /js/object
        - /js/inherit
        - /js/object-methods 
        - /js/copy
        - /js/knowledge-points
        - /js/array
        - /js/utils
    - title: JS进阶 
      collapsable: false
      sidebarDepth: 2
      children:
        - /js/call
        - /js/eventloop
        - /js/func-program
        - /js/design-mode
        - /js/algorithm
    - title: HTML/CSS
      collapsable: true
      sidebarDepth: 2
      children:
        - /hc/html
        - /hc/css-utils
    - title: ES6
      collapsable: true
      sidebarDepth: 2
      children:
        - /es6/class
        - /es6/promise
        - /es6/module
    - title: React
      collapsable: true
      sidebarDepth: 2
      children:
        - /react/lifecycle
        - /react/react-hooks
        - /react/redux
        - /react/redux-middleware
        - /react/async
        - /react/basic-co
        - /react/complex-co
    - title: Typescript
      collapsable: true
      sidebarDepth: 2
      children:
        - /typescript/ts-basic
        - /typescript/ts-axios
    - title: Node
      collapsable: true
      sidebarDepth: 2
      children:
        - /node/little-points
        - /node/blog   
        - /node/mysql
    - title: 工具
      collapsable: true
      sidebarDepth: 2
      children:
        - /tools/webpack/webpack-config
        - /tools/webpack/webpack-react
        - /tools/webpack/babel
        - /tools/git
        - /tools/tool
    - title: Vue
      collapsable: true
      sidebarDepth: 2
      children:
        - /vue/vuepress
    - title: 网络
      collapsable: true
      sidebarDepth: 2
      children:
        - /network/http-message
    - title: 服务器
      collapsable: true
      sidebarDepth: 2
      children:
        - /server/ubuntu
        - /server/linux 
        - /server/nginx 
    - title: 面试
      collapsable: true
      sidebarDepth: 2
      children:
        - /interview/js-interview
        - /interview/lib-interview 
        - /interview/other-interview
    - title: 其他
      collapsable: true
      sidebarDepth: 2
      children:
        - /others/words
        - /others/questions

    