title: 小白龙的博客
description: 小白龙的前端记录
locales:
  /:
    lang: zh-CN
    title: 小白龙的博客
    description: 小白龙的前端记录
head: 
  -
    - link
    -
      rel: icon
      href: /avatar.png
themeConfig :
  logo: /avatar.png
  nav:
    - text: Github
      link: https://github.com/xblcity
  sidebar: 
    - title: 介绍
      path: /
    - title: JS基础
      collapsable: false
      sidebarDepth: 2
      children:
        - /js/scope-closures
        - /js/this
        - /js/object
        - /js/inherit
        - /js/object-methods 
    - title: JS进阶 
      collapsable: false
      children:
        - /js/call
        - /js/copy
        - /js/eventloop
        - /js/func-program
        - /js/design-mode
    - title: ES6
      collapsable: false
      children:
        - /es6/class
        - /es6/super
        - /es6/promise
        - /es6/module
    - title: Typescript
      collapsable: false
      children:
        - /typescript/ts-basic
        - /typescript/ts-axios
    - title: React
      collapsable: false
      children:
        - /react/react-hooks
        - /react/redux
        - /react/redux-middleware
        - /react/react-redux
        - /react/lifecycle
        - /react/dynamic-data
        - /react/ui-component
        - /react/react-test
    - title: 工具
      collapsable: true
      children:
        - /tools/webpack/webpack
        - /tools/webpack/webpack-config
        - /tools/webpack/webpack-react
        - /tools/webpack/babel
        - /tools/git
        - /tools/tool
    - title: Node
      collapsable: true
      children:
        - /node/little-points
        - /node/blog       
    - title: 网络
      collapsable: true
      children:
        - /network/http-message
    - title: 服务器
      collapsable: true
      children:
        - /server/ubuntu
        - /server/linux 
        - /server/nginx 
    - title: 其他
      collapsable: true
      children:
        - /others/job-interview
        - /others/job-answers  
        - /others/words  
        - /others/questions
        - /others/little-points

    